---
# yamllint disable rule:line-length
- name: install when install_miniconda is true
  include_tasks: install.yml
  when: install_miniconda is defined and install_miniconda|bool

- name: Copy conda environment templates
  win_template:
    dest: 'C:/tmp/'
    src: "{{ item }}"
  with_items:
    - "{{ conda_templates }}"

- name: Configure conda environments
  win_shell: |
    cmd.exe {{ conda_dir }}/Scripts/activate.bat {{ conda_dir }}
    {{ conda_dir }}/condabin/conda env create -f C:/tmp/{{ item }}
  register: venv
  failed_when: venv.rc|int > 1
  with_items:
    - "{{ conda_templates }}"
  tags:
    - venv

- name: Cleanup conda
  win_shell: |
    cmd.exe {{ conda_dir }}/Scripts/activate.bat {{ conda_dir }}
    {{ conda_dir }}/condabin/conda clean --all
  tags:
    - cleanup
